use_frameworks!

target 'FMEarphoneSDK_Example' do
  pod 'FMEarphoneSDK', :path => '../'

  target 'FMEarphoneSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'FBSnapshotTestCase'
    pod 'OCMockito', '~> 5.0'
    
  end
end
